server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-server
  cloud:
    gateway:
      routes:
        - id: chat-server
          uri: lb://CHAT-SERVER
          predicates:
            - Path=/chat/**

      default-filters:
        - AuthorizationHeaderFilter
jwt:
  secret:
    key: J4uEieF9SiI2Y++yxKDMED4fyTUcpTWg7xpJ9pyzHZUGA6VlbVAlaNjG+X7hjWeHLfiiRWndh1c8oM/RGpaLDg==